### ISSUE TITLE
ERROR: Nothing reached the server. Skipping test...

### ISSUE THREAD

**Issue by Wmoinil** [daynix/NetMeter#3]
When running the tests I always get this result after 5min of running? 
Any solutions?

ERROR: Nothing reached the server. Skipping test...

**Comment by blochl** [comment]
Hi,
Are you sure that it's not an actual networking problem with your setup?
Did you check the logs in the **raw-data** subdirectory?
You can also try to launch the separate _iperf_ commands manually, and see what happens - the commands are also among the logs.
