### ISSUE TITLE
When letting Netmeter generate and transfer ssh keys: ssh_port variable not defined

### ISSUE THREAD

**Issue by maxnet** [daynix/NetMeter#5]
One more small thing.
If you let Netmeter generate and transfer SSH keys, it errors out because ssh_port is not defined here: https://github.com/daynix/NetMeter/blob/master/NetMeter.py#L195

(Not a big issue, as running ssh-copy-id manually is easy enough. But reporting it anyway).

**Comment by blochl** [comment]
If you know how to fix it, can you please send a pull request? I am not actively using NetMeter now, and have no way to test it myself. Thanks for reporting!!
